import { Mob } from './types';

export const BOSS_MONSTERS: Mob[] = [
  { id: 1, name: 'Chatacabra', zhName: '纏蛙', className: 'chatacabra' },
  { id: 2, name: 'Quematrice', zhName: '炎尾龍', className: 'quematrice' },
  { id: 3, name: 'Lala Barina', zhName: '刺花蜘蛛', className: 'lala-barina' },
  { id: 4, name: 'Congalala', zhName: '桃毛獸王', className: 'congalala' },
  { id: 5, name: 'Balahara', zhName: '沙海龍', className: 'balahara' },
  { id: 6, name: 'Doshaguma', zhName: '闢獸', className: 'doshaguma' },
  { id: 7, name: 'Uth Duna', zhName: '波衣龍', className: 'uth-duna' },
  { id: 8, name: 'Rompopolo', zhName: '沼噴龍', className: 'rompopolo' },
  { id: 9, name: 'Rey Dau', zhName: '煌雷龍', className: 'rey-dau' },
  { id: 10, name: 'Nerscylla', zhName: '影蜘蛛', className: 'nerscylla' },
  { id: 11, name: 'Hirabami', zhName: '風鋏龍', className: 'hirabami' },
  { id: 12, name: 'Ajarakan', zhName: '赫猿獸', className: 'ajarakan' },
  { id: 13, name: 'Nu Udra', zhName: '獄焰鱆', className: 'nu-udra' },
  { id: 14, name: 'Guardian Doshaguma', zhName: '護闢獸', className: 'guardian-doshaguma' },
  { id: 15, name: 'Guardian Rathalos', zhName: '護火龍', className: 'guardian-rathalos' },
  { id: 16, name: 'Jin Dahaad', zhName: '凍峰龍', className: 'jin-dahaad', oneSize: true },
  { id: 17, name: 'Guardian Ebony Odogaron', zhName: '護兇爪龍', className: 'guardian-ebony-odogaron' },
  { id: 18, name: 'Xu Wu', zhName: '暗器鱆', className: 'xu-wu' },
  { id: 19, name: 'Guardian Arkveld', zhName: '護鎖刃龍', className: 'guardian-arkveld', oneSize: true },
  { id: 20, name: 'Zoh Shia', zhName: '白熾龍', className: 'zoh-shia', oneSize: true },
  { id: 21, name: 'Yian Kut Ku', zhName: '怪鳥', className: 'yian-kut-ku' },
  { id: 22, name: 'Gypceros', zhName: '毒怪鳥', className: 'gypceros' },
  { id: 23, name: 'Rathian', zhName: '雌火龍', className: 'rathian' },
  { id: 24, name: 'Guardian Fulgur Anjanath', zhName: '護雷顎龍', className: 'guardian-fulgur-anjanath' },
  { id: 25, name: 'Rathalos', zhName: '火龍', className: 'rathalos' },
  { id: 26, name: 'Gravios', zhName: '鎧龍', className: 'gravios' },
  { id: 27, name: 'Blangonga', zhName: '雪獅子王', className: 'blangonga' },
  { id: 28, name: 'Gore Magala', zhName: '黑蝕龍', className: 'gore-magala' },
  { id: 29, name: 'Arkveld', zhName: '鎖刃龍', className: 'arkveld' },
];
